name: CI Pipeline

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  # Job 1: Basic Checks
  test:
    name: Test & Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Job 2: Summary
  summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    
    steps:
      - name: Create Summary
        run: |
          echo "##  CI Pipeline Results" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Author:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "-  Tests: ${{ needs.test.result }}" >> $GITHUB_STEP_SUMMARY