name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install packages
        run: npm install

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Run Playwright tests
        run: npx playwright test

      - name: Save test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: playwright-report/
