name: CI Pipeline

on:
  push:
    branches: 
      - master
      - develop
      - 'feature/**'
      - 'refactor/**'
  pull_request:
    branches: 
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  # Job 1: Basic Checks
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Run Linting
        run: |
          npm run lint || echo "::warning::No lint script found"

      - name: Run Tests
        run: |
          npm test || npm run test || echo "::warning::No test script found"

  # Job 2: Playwright E2E Tests
  playwright-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: lint-and-test
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run Playwright Tests
        run: npx playwright test
        env:
          CI: true

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  # Job 3: Build Check
  build:
    name: Build Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: lint-and-test
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Build Project
        run: |
          npm run build || npx tsc || echo "::warning::No build script found"

  # Job 4: Summary
  summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [lint-and-test, playwright-tests, build]
    if: always()
    
    steps:
      - name: Create Summary
        run: |
          echo "##  Pipeline Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Author:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Job Status:" >> $GITHUB_STEP_SUMMARY
          echo "- Lint & Test: ${{ needs.lint-and-test.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Playwright Tests: ${{ needs.playwright-tests.result }}" >> $GITHUB_STEP_SUMMARY  
          echo "- Build: ${{ needs.build.result }}" >> $GITHUB_STEP_SUMMARY
